import 'package:blog/domain/entities/cuisine.entity.dart';

List<CuisineEntity> foods = [
  CuisineEntity(
    title: 'Sinigang',
    desc:
        "Sinigang is a popular Filipino soup known for its sour and savory flavors. It is traditionally made with tamarind as the souring agent, although other fruits like guava, green mango, or calamansi can be used as well. The soup is usually prepared with pork, beef, shrimp, or fish, and it is loaded with an assortment of vegetables such as radishes, green beans, eggplant, and leafy greens like kangkong (water spinach). The sour broth is complemented by the natural sweetness of the vegetables, creating a delightful balance of flavors. Sinigang is often served hot and enjoyed with steamed rice, providing a comforting and satisfying meal, especially during rainy days or colder seasons.",
    image:
        'https://i.pinimg.com/564x/4a/1a/cf/4a1acfb5d1cc72acfe1f182dd61db13e.jpg',
    isFavorite: true,
    procedure: const [
      '1.	Heat the pot and put-in the cooking oil',
      '2.	Sauté the onion until its layers separate from each other',
      '3.	Add the pork belly and cook until outer part turns light brown',
      '4.	Put-in the fish sauce and mix with the ingredients',
      '5.	Pour the water and bring to a boil',
      '6.	Add the taro and tomatoes then simmer for 40 minutes or until pork is tender',
      '7.	Put-in the sinigang mix and chili',
      '8.	Add the string beans (and other vegetables if there are any) and simmer for 5 to 8 minutes',
      '9.	Put-in the spinach, turn off the heat, and cover the pot. Let the spinach cook using the remaining heat in the pot.',
      '10.	Serve hot. Share and enjoy!',
    ],
    ingredients: const [
      '•	8 cups of water',
      '•	2 medium-sized red onions quartered',
      '•	4 medium-sized tomatoes quartered',
      '•	1 kilo pork cubed',
      '•	1 pack (44 grams) Knorr Sinigang sa Sampaloc Mix with Gabi',
      '•	3 pieces taro (gabi) peeled and quartered',
      '•	2 pieces radish (labanos) peeled and sliced',
      '•	1 bunch string beans (sitaw) cut into 1-inch long pieces',
      '•	6 to 8 pieces okra',
      '•	2 pieces eggplants sliced',
      '•	3 pieces green chili (siling tagalog)',
      '•	4 tablespoons fish sauce (patis)',
      '•	1 bunch kangkong (water spinach) leaves tender stems pinched off',
    ],
    notes: const [
      '•	This recipe can also be used for beef, chicken, and fish.',
      '•	Souring agents also include tamarind, bilimbi, unripe mango, and calamansi. I used “sinigang mix” for this recipe  for convenience. It also gives the exact amount of sourness that I like for my sinigang.',
      '•	Taro is nice to have. It will give your soup a thicker texture. However, you can still make this dish without it.',
      '•	Sliced daikon radish are used in some version. Feel free to add some if preferred.',
      '•	I used spinach for this recipe. A more traditional approach is the use of water spinach (kangkong).',
      '•	If spinach or water spinach are not available, you can use bok choy.',
    ],
  ),
  CuisineEntity(
    title: 'Chicken Tinola',
    desc:
        "Tinola is a traditional Filipino comfort food that usually consists of broth, chicken, leafy greens, papaya, and ginger. Fish sauce is a key ingredient that lends a deliciously pungent taste. Chicken tinola is often served with rice to make a hearty meal.",
    image:
        'https://i.pinimg.com/736x/5d/59/e9/5d59e99a56f7029d0e679ad0431da027.jpg',
    isFavorite: false,
    procedure: const [
      '1.	Gather all ingredients.',
      '2.	Heat oil in a large pot over medium heat. Add onion and garlic; cook and stir until fragrant, about 2 minutes.',
      '3.	Add ginger and fish sauce; cook and stir for 1 to 2 minutes. Stir in chicken and cook for 5 minutes.',
      '4.	Pour in chicken broth and cook for 5 minutes. Add squash and simmer until chicken is no longer pink in the center, about 10 minutes. Season with salt and pepper.',
      '5.	Add bok choy and spinach; cook until spinach is just wilted, 1 to 2 minutes. Serve hot.',
    ],
    ingredients: const [
      '•	1 tablespoon cooking oil',
      '•	1 medium onion, chopped',
      '•	2 cloves garlic, minced',
      '•	1 (1 1/2 inch) piece fresh ginger, peeled and thinly sliced',
      '•	1 tablespoon fish sauce',
      '•	3 pounds chicken legs and thighs, rinsed and patted dry',
      '•	2 (14 ounce) cans chicken broth',
      '•	1 chayote squash, peeled and cut into bite-sized pieces salt and ground black pepper to taste',
      '•	1 head bok choy, chopped',
      '•	1 (8 ounce) package fresh spinach, chopped',
    ],
    notes: const [],
  ),
  CuisineEntity(
    title: 'Chicken Adobo',
    desc:
        "Chicken Adobo is an authentic Filipino dish and is one of the mostly recognized Filipino foods. Not to be mistaken with Mexican adobo, this dish is uniquely prepared by stewing chicken in vinegar and soy sauce.",
    image:
        'https://i.pinimg.com/564x/4a/1a/cf/4a1acfb5d1cc72acfe1f182dd61db13e.jpg',
    isFavorite: false,
    procedure: const [
      '1.	Heat vegetable oil in a large skillet over medium-high heat. Cook chicken pieces until golden brown, 2 to 3 minutes per side. Transfer chicken to a plate and set aside.',
      '2.	Add onion and garlic to the skillet; cook until softened and brown, about 6 minutes.',
      '3.	Pour in soy sauce and vinegar and season with garlic powder, black pepper, and bay leaf.',
      '4.	Return chicken to pan, increase heat to high, and bring to a boil. Reduce heat to medium-low, cover, and simmer until chicken is tender and cooked through, 35 to 40 minutes.',
    ],
    ingredients: const [
      '•	2 tablespoons vegetable oil',
      '•	1 (3 pound) chicken, cut into pieces',
      '•	1 large onion, quartered and sliced',
      '•	2 tablespoons minced garlic',
      '•	⅔ cup low sodium soy sauce',
      '•	⅓ cup white vinegar',
      '•	1 tablespoon garlic powder',
      '•	2 teaspoons black pepper',
      '•	1 bay leaf',
    ],
    notes: const [],
  ),
  CuisineEntity(
    title: 'Bicol Express',
    desc:
        "Bicol Express is a popular Filipino dish known for its spicy and flavorful taste. It originated from the Bicol region in the Philippines, hence the name. The dish is primarily made with pork, coconut milk, and a variety of chili peppers. To prepare Bicol Express, pork is typically simmered in coconut milk until tender. The dish gets its spiciness from the addition of chili peppers, particularly the native Bicol chilies called \"siling labuyo.\" Other ingredients such as garlic, onions, ginger, and shrimp paste are commonly used to enhance the flavors. The resulting dish is a rich and creamy stew with a kick of heat from the chilies. It is often enjoyed with steamed rice and is a favorite among those who appreciate spicy cuisine. Bicol Express has become a popular Filipino comfort food and is a must-try for those who enjoy the combination of pork, coconut, and spicy flavors.",
    image:
        'https://speedyrecipe.com/wp-content/uploads/2019/05/How-to-Cook-Bicol-Express.jpg',
    isFavorite: true,
    procedure: const [
      '1.	Heat a pan and then pour-in the cooking oil.',
      '2.	Sauté the garlic, onion, and ginger.',
      '3.	Add the pork and cook for 8 minutes or until the color becomes light brown.',
      '4.	Mix then coconut milk and alamang (shrimp paste).',
      '5.	Bring to a boil, lower heat and then simmer for 10 minutes.',
      '6.	Add chili peppers and cook until half the liquid has evaporated.',
      '7.	Add the long chili (siling haba/panigang).',
      '8.	Pour in thick coconut cream and continue cooking until oil comes out from the cream.',
      '9.	Add salt and ground black pepper to taste.',
      '10.	Serve hot.',
    ],
    ingredients: const [
      '•	1/2 lb. pork belly, diced',
      '•	2 cup thin coconut milk',
      '•	2 tablespoon fresh alamang (shrimp paste)',
      '•	10 pieces Thai chili pepper, stemmed and minced',
      '•	6 pieces long chili (siling haba, siling panigang), sliced',
      '•	3 cloves garlic, minced',
      '•	1 medium-sized onion, minced',
      '•	1 cup thick coconut cream',
      '•	3 tablespoon minced ginger',
      '•	salt and pepper to taste',
    ],
    notes: const [],
  ),
  CuisineEntity(
    title: 'kare-kare',
    desc:
        "Kare-Kare is a traditional Filipino dish known for its rich and savory flavors. It is a stew made with a thick peanut sauce and typically includes a variety of vegetables, as well as meat such as oxtail, beef tripe, or pork hocks. Kare-Kare is often served with steamed rice and accompanied by a side of shrimp paste. It is a well-loved dish in Filipino cuisine, enjoyed for its unique combination of creamy peanut sauce, tender meat, and vibrant vegetables.",
    image:
        'https://www.unileverfoodsolutions.com.ph/dam/global-ufs/mcos/SEA/calcmenu/recipes/PH-recipes/red-meats-&-red-meat-dishes/kare-kare/kare-kare-main.jpg',
    isFavorite: true,
    procedure: const [
      '1.	Rinse oxtail under cold, running water and with a knife, trim excess fat. In a deep pot, place oxtails and enough water to cover. Over medium heat, bring to a boil, skimming any scum that accumulates to top. Lower heat, cover and simmer, adding more water as needed to maintain 6 cups, for about 2 to 3 hours or until oxtails are easily pierced with a fork. Drain oxtail, reserving about 6 cups broth.',
      '2.	Peel and discard the outer, fibrous skin layers of banana heart until you reach the lighter, softer core. Trim off stem and discard. Cut banana core into half and into fourths. In a bowl of cold salted water, place cut banana and soak for about 15 to 20 minutes. Using hands, squeeze to release bitter sap. Rinse with cold water and drain well, discarding liquid.',
      '3.	In a pot over medium heat, bring about 4 cups water to a boil. Add banana heart and blanch for about 1 minute. With a slotted spoon, remove from liquid and set aside. Add eggplant and blanch for about 1 minute. With a slotted spoon, remove from liquid and set aside. Add long beans and blanch for about 1 minute. With a slotted spoon, remove from liquid and set aside. Add pechay and blanch for about 30 seconds. With a slotted spoon, remove from liquid and set aside.',
      '4.	In a skillet over medium heat, add rice flour and cook, stirring occasionally, until lightly browned and toasted. In a bowl, combine toasted rice flour and ¼ cup reserved broth and whisk until smooth.',
      '5.	In a small bowl, combine annatto powder and ¼ cup reserved broth. Stir until powder is dissolved and color has dispersed.',
      '6.	In a bowl, combine peanut butter and ½ cup of reserved broth and stir until well-blended.',
      '7.	In a large pot over medium heat, heat oil. Add onions and garlic and cook until limp and aromatic. Add oxtail and cook, stirring occasionally, until lightly browned. Add fish sauce and cook for about 2 to 3 minutes.',
      '8.	Add the remaining 5 cups of reserved broth and bring to a simmer. Add annatto water, rice flour mixture and peanut butter mixture, stirring well to combine. Season with salt and pepper to taste. Continue to simmer for about 10 minutes or until it begins to slightly thicken. Add blanched vegetables and cook for about 2 to 3 minutes or until heated through and tender yet crisp. Serve hot with shrimp paste on the side.',
    ],
    ingredients: const [
      '•	2 pounds oxtail cut into serving size',
      '•	water',
      '•	1 banana heart',
      '•	2 large eggplant ends trimmed and cut into 1-inch thick',
      '•	1 bundle long beans sitaw, cut into 3-inch lengths',
      '•	1 bundle pechay ends trimmed and leaves separated',
      '•	¼ cup rice flour',
      '•	1-½ tablespoons annatto powder',
      '•	1-½ cups chunky peanut butter',
      '•	1 tablespoon oil',
      '•	1 medium onion peeled and sliced thinly',
      '•	4 to 5 cloves garlic peeled and minced',
      '•	2 tablespoons fish sauce',
      '•	salt and pepper to taste',
      '•	shrimp paste',
    ],
    notes: const [],
  ),
  CuisineEntity(
    title: 'laing (taro leaves in coconut milk)',
    desc:
        "Laing is a classic Filipino dish that hails from the Bicol region, known for its use of taro leaves and coconut milk. It is a flavorful and creamy vegetable dish that is popular in Filipino cuisine. Laing is typically served with steamed rice and enjoyed as a main dish or a side dish. It is a beloved Filipino comfort food, appreciated for its unique blend of flavors and the creamy texture of the taro leaves cooked in coconut milk.",
    image:
        'https://www.knorr.com/content/dam/unilever/knorr_world/philippines/photography_and_pictures/bicolano-laing-recipe-89746311-jpg.jpg.ulenscale.1320x742.jpg',
    isFavorite: false,
    procedure: const [
      '1.	In a large pan over medium heat, spread out your pork belly strips and pour water over until meat is covered. Place the lid on and and cook until all liquid has evaporated and the pork fat has started to render.',
      '2.	Combine the shrimp paste, garlic, coconut milk and ginger in the pan and stir for about 2 minutes.',
      '3.	Add the taro (gabi) leaves and let it absorb the coconut milk. Avoid stirring the leaves. Let this boil and dry up for about 10 minutes.',
      '4.	Add in the kakang gata or coconut cream, green chilies and bird s eye chilies. Again, leave to boil or dry up for another 10 minutes. Add more chillies, if preferred. Serve warm with rice and other viands.',
    ],
    ingredients: const [
      '•	200 Grams taro leaves (dahon ng gabi) (use dried leaves), (dried gabi leaves)',
      '•	4 slices pork cut into 1/4 inch-thick strips',
      '•	2 to 4 tablespoons shrimp paste (bagoong alamang) to taste',
      '•	4 cloves Garlic chopped',
      '•	6 cups coconut milk (gata)',
      '•	4 cups coconut cream (kakang gata) or coconut cream',
      '•	2 thumb-sized piece ginger cut into large strips',
      '•	8 pieces green finger chili (siling pangsigang) cut into 1-inch pieces',
      '•	4 pieces red chili pepper (siling labuyo) sliced thinly',
    ],
    notes: const [
      '•	As other types of leaves might have gotten mixed in during the drying process, check the dried gabi packet for any stray leaves and discard them.',
      '•	Two ounces might not look like a lot, but the dried leaves will absorb much of the liquid and expand during cooking.',
      '•	According to old-school wisdom, it\'s also best not to stir the taro leaves in the pot during the first 15 to 20 minutes to prevent the irritating sensation. Gently push the leaves down into the coconut milk to soften them.',
      '•	Cook the coconut sauce at a gentle simmer, and do not boil lest it curdles or separates.',
      '•	Adjust the spiciness by decreasing the number of chili peppers or scraping off the seeds and veins of the chilies before chopping.',
    ],
  ),
  CuisineEntity(
    title: 'kilayin',
    desc:
        "Kilayin is a classic Kapampangan-style kilawin you need to try! This pork and liver stew cooked in vinegar and spices is full-on flavor and delicious with steamed rice. Kilawin kapampangan or popularly known as \"kilayin\" is a kapampangan dish made from minced pork lungs, chopped pork meat and liver, stewed in vinegar with spices and aromatics.",
    image:
        'https://www.kawalingpinoy.com/wp-content/uploads/2015/07/kapampangan-kilayin-1.jpg',
    isFavorite: false,
    procedure: const [
      '  1.	In one bowl, combine pork and ½ cup of the vinegar, 1 teaspoon salt, and ¼ teaspoon pepper. Marinate for about 30 minutes.',
      '2.	In another bowl, combine the liver, heart, the remaining ½ cup of the vinegar, 1 teaspoon salt, and ¼ teaspoon pepper. Marinate for about 30 minutes.',
      '3.	After marinating, drain pork from marinade and squeeze excess liquid. Reserve marinade.',
      '4.	Drain liver and heart from marinade and squeeze excess liquid. Reserve marinade.',
      '5.	In a pan over medium heat, heat oil. Add onions and garlic and cook until softened.',
      '6.	Add minced lung and cook, stirring occasionally, until browned and sizzling.',
      '7.	Add pork and cook until lightly browned.',
      '8.	Add fish sauce and cook, stirring occasionally, for about 2 to 3 minutes.',
      '9.	Add reserved vinegar marinade and bring to a boil, uncovered and without stirring, for about 3 to 5 minutes. Lower heat, cover and cook until pork is tender.',
      '10.	Add liver and heart and continue to cook for about 3 to 5 minutes or until cooked through and sauce is reduced.',
      '11.	Season with salt and pepper if needed. Serve hot.',
    ],
    ingredients: const [
      '•	1 pound pork shoulder, cut into 1-inch strips',
      '•	1 pound liver, cut into 1-inch strips',
      '•	1 piece pork heart, cut into 1-inch strips',
      '•	1 cup vinegar',
      '•	salt and pepper',
      '•	2 tablespoon oil',
      '•	3 cloves garlic, peeled and minced',
      '•	1 onion, peeled and chopped',
      '•	½ pound pork lung, minced',
      '•	1 tablespoon fish sauce',
    ],
    notes: const [
      '•	Do not marinate for too long, as the acids in the vinegar might break down the protein fibers and make the meat mushy. Plan for thirty minutes to an hour.',
      '•	When added to the pan, give the vinegar a few minutes to boil uncovered and without stirring to cook off the strong acid taste.',
    ],
  ),
  CuisineEntity(
    title: 'Paksiw na Bangus',
    desc:
        "Filipino’s Paksiw is vinegar base, and we all know that vinegar is a liquid ingredient that helps preserve food longer, so there’s no worry even if you put it in the fridge and let it stay there for weeks. Also, vinegar is a perfect partner of any fish as it removes the fishy odor, which anyone hates.Milkfish commonly lives in tropical offshore marine waters around the islands and along continental shelves, at depths of 1 to 30 m. They also frequently enter estuaries and rivers.Fish is low in Sodium. It is also a good source of Vitamin B6 that is important for normal brain development and keeps the nervous system and immune system healthy.",
    image:
        'https://nutriasia.com/wp-content/uploads/2020/05/PAKSIW-NA-BANGUS-WITH-TAUSI-1200x900.jpg',
    isFavorite: false,
    procedure: const [
      '1.	Place ginger then the bangus in a wide pan. Topped with garlic, salt, ground pepper, vinegar and water.',
      '2.	Bring into a boil uncovered over medium high heat. Once it starts to boil, reduce heat to medium low and add Ampalaya, Siling Haba and onion slices. Simmer for 5 to 10 minutes or until Bangus and Ampalaya are fully cooked.',
      '3.	Add cooking oil and simmer for few minutes.',
      '4.	Garnish with slices of green onion and serve hot. Enjoy!',
    ],
    ingredients: const [
      '•	1 Large (1 1/2 to 2 lb) Bangus Cut into 6-8 pieces and cleaned',
      '•	1 Cup Vinegar',
      '•	2 Large Ampalaya (optional) Cleaned and sliced thick',
      '•	2-3 pcs Siling Haba',
      '•	2 Thumb size Ginger Sliced thin',
      '•	4-5 Gloves Garlic Sliced thin',
      '•	1 Medium Red Onion Sliced',
      '•	½ Cup Water',
      '•	2 tbs Cooking Oil',
      '•	Salt and Ground Pepper',
    ],
    notes: const [],
  ),
  CuisineEntity(
    title: 'Bopis',
    desc:
        "Bopis is a spicy Filipino delicacy made of minced pork lung and heart cooked in onions, garlic, and chili peppers. Popular as an appetizer, it is also commonly served as a main meal entree. Like adobo, afritada, and other Filipino classics, there are many regional interpretations of this dish. Depending on the local version, the ingredients and seasonings may include tomato sauce, paprika, radish (labanos), carrots, bell peppers, and vinegar. While some variations have a more saucy consistency due to the use of tomato sauce, Kapampangan bopis is mostly dry.",
    image:
        'https://i.pinimg.com/564x/66/db/a0/66dba0cc903579a5d0ec375cccde63a0.jpg',
    isFavorite: false,
    procedure: const [
      ' 1.	In a bowl, combine minced pork lung (or bopis mix), vinegar, and salt. Marinate for about 10  minutes.',
      '2.	In a wide skillet over medium heat, heat oil. Add onions and garlic and cook until softened.',
      '3.	Add fish sauce.',
      '4.	Add minced pork lungs and bring to a boil. Cook, stirring occasionally, for about 20 to 30 minutes or until liquid is mostly absorbed and meat begins to sizzle.',
      "5.	Add carrots, bell peppers, and chili peppers. Continue to cook for about 2 to 3 minutes or until vegetables are tender-crisp.",
    ],
    ingredients: const [
      '•	2 pounds minced pork lungs',
      '•	½ cup vinegar',
      '•	1 teaspoon salt',
      '•	2 tablespoons canola oil',
      '•	1 onion, peeled and chopped'
          '•	4 cloves garlic, peeled and minced',
      '•	1 tablespoon fish sauce',
      '•	1 large carrot, peeled and diced',
      '•	½ green bell pepper, seeded and chopped',
      '•	½ red bell pepper, seeded and chopped',
      '•	4 Thai chili peppers, stemmed and chopped',
    ],
    notes: const [],
  ),
  CuisineEntity(
    title: 'Pinakbet',
    desc:
        "Pinakbet is a vegetable-based dish from the Philippines that can be served as an everyday dish or when you have company. Since it also contains pork and prawns, you can eat it as a one-pot meal.",
    image:
        'https://i.pinimg.com/564x/49/d9/a8/49d9a8b364a2199bf7bf7909966c3181.jpg',
    isFavorite: false,
    procedure: const [
      '1.	Heat oil in a large pot over medium heat; stir in onion and garlic and cook until tender, about 5 minutes.',
      '2.	Add pork; cook and stir until browned, 5 to 7 minutes.',
      '3.	Add prawns; cook and stir until they turn pink, about 5 minutes.',
      '4.	Stir in tomato; season with salt and pepper, cover and simmer for 5 minutes.',
      '5.	Stir in zucchini, okra, green beans, eggplant, and bitter melon; cover and cook until the vegetables are tender, about 10 minutes.',
    ],
    ingredients: const [
      '•	3 tablespoons olive oil',
      '•	1 onion, chopped',
      '•	2 cloves garlic, minced',
      '•	½ pound pork loin, chopped',
      '•	½ pound peeled and deveined prawns',
      '•	salt and pepper to taste',
      '•	1 tomato, chopped',
      '•	¼ pound zucchini, seeded and cut into bite-size pieces',
      '•	¼ pound fresh okra, ends trimmed',
      '•	¼ pound fresh green beans, trimmed',
      '•	¼ pound eggplant, cut into bite-size pieces',
      '•	1 small bitter melon, cut into bite-size pieces',
    ],
    notes: const [],
  ),
];
